### PR TITLE
Prepare lib for Odoo PDF import

### PR DESCRIPTION
**Pull request by alexis-via**
This PR contains my work of these last days on this lib to make it work with my module on Odoo PDF import.

The fact is that I modified several different things:
- try to fix bug #1 
- add UTF-8 headers
- update date parsing
- add templates for several French companies

This is still a bit a "work in progress", as I'll continue to work on this branch in the coming days. But this PR should help you see what changes I'm doing and maybe get your feedback if you disagree on some changes I make.

### CODE REVIEW

**Comment by manuelRiel** [comment]
Awesome. Can you also add some sample files, so I can try out the new templates? And maybe add them to a test folder? Just drop them here. No need to add them in the PR.

**Comment by alexis-via** [comment]
@manuelRiel 
I'm glad that you like my work.
FYI, the code of my Odoo module that use your invoice2data lib is here: https://github.com/akretion/account-invoicing/tree/8.0-add-pdf-invoice-import/account_invoice_pdf_import (AGPL licence)

About the template files: I should be able to add a few, but I got some of them via friends and I told them that I would keep their invoice confidential. Some of them are phone bill invoices with detailed call records, so you can understand that it's not a good idea for privacy reasons to add it to the "test" folder... but in the meantime I understand the need to have a test suite to check the templates.

**Comment by alexis-via** [comment]
@manuelRiel FYI, I just announced the availability of the Odoo module "account_invoice_pdf_import" on my company blog: http://www.akretion.com/blog/akretions-christmas-present-for-the-odoo-community So you will know the story behind our work !

I hope it will bring more contributors to your great project.

**Comment by manuelRiel** [comment]
Thanks for the contribution. I added a license, merged your code and added you to contributors. And will upload to Pypi.

I'll probably work on this again when I do my own accounting. What other features would be interesting? The main goal is to recognize new invoices without templates. But to train a ML algo, I don't have enough sample data right now.

**Pull request merged**
